#!/bin/bash
#============================================================
# 粤商汇 - 快速部署指南
# 从本地代码到阿里云服务器的完整部署流程
#============================================================

# 颜色定义
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo ""
echo "============================================================"
echo "       粤商汇 - 阿里云部署指南"
echo "============================================================"
echo ""
echo "本指南将帮助您将项目部署到阿里云轻量应用服务器"
echo ""

echo -e "${BLUE}【第一步】购买阿里云轻量应用服务器${NC}"
echo "  1. 访问: https://www.aliyun.com/product/swas"
echo "  2. 选择配置:"
echo "     - 地域: 华南1(深圳) 或 华东1(杭州)"
echo "     - 镜像: Ubuntu 22.04 LTS"
echo "     - 套餐: 2核2G (¥60/月左右)"
echo "  3. 设置 root 密码"
echo "  4. 在安全组中开放端口: 22, 80, 443, 3000"
echo ""

echo -e "${BLUE}【第二步】上传代码到服务器${NC}"
echo ""
echo "  方式一: 使用 scp 命令"
echo "  -------------------"
echo "  # 打包项目代码"
echo "  tar -czf yueshanghui.tar.gz \\"
echo "    --exclude=node_modules \\"
echo "    --exclude=.git \\"
echo "    --exclude=dist \\"
echo "    ."
echo ""
echo "  # 上传到服务器"
echo "  scp yueshanghui.tar.gz root@YOUR_SERVER_IP:/tmp/"
echo ""
echo "  # SSH 登录服务器并解压"
echo "  ssh root@YOUR_SERVER_IP"
echo "  mkdir -p /var/www/yueshanghui"
echo "  tar -xzf /tmp/yueshanghui.tar.gz -C /var/www/yueshanghui"
echo ""
echo "  方式二: 使用 Git"
echo "  ----------------"
echo "  # SSH 登录服务器"
echo "  ssh root@YOUR_SERVER_IP"
echo ""
echo "  # 克隆代码"
echo "  git clone YOUR_REPO_URL /var/www/yueshanghui"
echo ""

echo -e "${BLUE}【第三步】初始化服务器环境${NC}"
echo "  -------------------"
echo "  # SSH 登录服务器"
echo "  ssh root@YOUR_SERVER_IP"
echo ""
echo "  # 进入项目目录"
echo "  cd /var/www/yueshanghui"
echo ""
echo "  # 运行初始化脚本"
echo "  sudo bash deploy/setup-server.sh"
echo ""

echo -e "${BLUE}【第四步】配置环境变量${NC}"
echo "  -------------------"
echo "  # 复制环境变量模板"
echo "  cp .env.example .env"
echo ""
echo "  # 编辑环境变量"
echo "  vim .env"
echo ""
echo "  # 必填项:"
echo "  # - SUPABASE_URL: Supabase 项目 URL"
echo "  # - SUPABASE_SERVICE_ROLE_KEY: Supabase Service Role Key"
echo "  # - PROJECT_DOMAIN: 您的域名 (如 https://yueshanghui.com)"
echo "  # - JWT_SECRET: 使用 openssl rand -hex 32 生成"
echo ""

echo -e "${BLUE}【第五步】执行部署${NC}"
echo "  -------------------"
echo "  # 一键部署"
echo "  bash deploy/deploy.sh --full"
echo ""

echo -e "${BLUE}【第六步】配置域名 (可选)${NC}"
echo "  -------------------"
echo "  # 1. 在域名服务商处添加 A 记录指向服务器 IP"
echo ""
echo "  # 2. 修改 Nginx 配置中的 server_name"
echo "  vim /etc/nginx/sites-available/yueshanghui.conf"
echo "  # 将 your-domain.com 改为您的实际域名"
echo ""
echo "  # 3. 申请 SSL 证书"
echo "  certbot --nginx -d your-domain.com -d www.your-domain.com"
echo ""
echo "  # 4. 重载 Nginx"
echo "  systemctl reload nginx"
echo ""

echo -e "${BLUE}【第七步】验证部署${NC}"
echo "  -------------------"
echo "  # 查看服务状态"
echo "  bash deploy/deploy.sh --status"
echo ""
echo "  # 查看后端日志"
echo "  pm2 logs yueshanghui-api"
echo ""
echo "  # 测试 API"
echo "  curl http://localhost:3000/api/health"
echo ""

echo ""
echo "============================================================"
echo -e "${GREEN}部署完成!${NC}"
echo "============================================================"
echo ""
echo "访问地址:"
echo "  - H5网页: http://YOUR_SERVER_IP"
echo "  - API接口: http://YOUR_SERVER_IP/api"
echo ""
echo "常用运维命令:"
echo "  - 查看状态: bash deploy/deploy.sh --status"
echo "  - 查看日志: pm2 logs yueshanghui-api"
echo "  - 重启服务: pm2 restart yueshanghui-api"
echo "  - 重新部署: bash deploy/deploy.sh --full"
echo "  - 回滚版本: bash deploy/deploy.sh --rollback"
echo ""
echo "如需帮助，请查看:"
echo "  - bash deploy/deploy.sh --help"
echo ""
