/** 管理台列表查询列：排除 LONGTEXT / 大 JSON，降低内存与网络占用 */

export const ADMIN_MEMBER_LIST_COLUMNS = [
  'id',
  'name',
  'phone',
  'avatar',
  'company_name',
  'company_position',
  'industry_primary',
  'membership_level',
  'status',
  'user_category',
  'invite_code',
  'referrer_id',
  'available_points',
  'total_points',
  'active_score',
  'credit_score',
  'join_source',
  'created_at',
  'updated_at',
].join(', ')

export const ADMIN_EVENT_LIST_COLUMNS = [
  'id',
  'title',
  'cover_image',
  'video_url',
  'event_type',
  'status',
  'start_time',
  'end_time',
  'location',
  'address',
  'max_participants',
  'current_participants',
  'fee',
  'is_featured',
  'sort_order',
  'view_count',
  'created_at',
  'updated_at',
  'admin_operated_at',
].join(', ')

export const ADMIN_ARTICLE_LIST_COLUMNS = [
  'id',
  'title',
  'subtitle',
  'summary',
  'cover_image',
  'video_url',
  'category',
  'tags',
  'author',
  'status',
  'view_count',
  'created_at',
  'updated_at',
].join(', ')

export const ADMIN_MALL_PRODUCT_LIST_COLUMNS = [
  'id',
  'name',
  'image_url',
  'video_url',
  'points_price',
  'cash_price',
  'stock',
  'category',
  'status',
  'sort_order',
  'sales_count',
  'view_count',
  'enable_distribution',
  'distribution_rate',
  'owner_member_id',
  'project_id',
  'created_at',
  'updated_at',
].join(', ')
